version: '2'

services:
  api-dotnet:
    build:
      context: .
      dockerfile: Dockerfile.debug
    environment:
      - REMOTE_DEBUGGING=${REMOTE_DEBUGGING}
    ports:
      - "5000:80"
    volumes:
      - .:/app
  web-node:
    image: stevelasker/web-node
    ports:
      - 80:3000
    environment:
      - HTTPPORT=3000
      - APIPORT=80
