FROM microsoft/dotnet:1.0.0-preview1
ENV NUGET_XMLDOC_MODE skip
ARG CLRDBG_VERSION=VS2015U2
ADD https://raw.githubusercontent.com/Microsoft/MIEngine/getclrdbg-release/scripts/GetClrDbg.sh /clrdbg/
WORKDIR /clrdbg
RUN chmod 700 GetClrDbg.sh
RUN ./GetClrDbg.sh $CLRDBG_VERSION
WORKDIR /app
EXPOSE 5000
ENTRYPOINT ["/bin/bash", "-c", "if [ -z \"$REMOTE_DEBUGGING\" ]; then dotnet api-dotnet.dll; else sleep infinity; fi"]
COPY . /app
