version: '2'

services:
  api-dotnet:
    image: stevelasker/api-dotnet:debug
    ports:
      - "5000:5000"
    environment:
      - REMOTE_DEBUGGING
    labels:
      com.stevelasker/api-dotnet.environment: "debug"
