version: '2'

services:
  api-dotnet:
    image: stevelasker/api-dotnet:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    environment:
      - REMOTE_DEBUGGING=${REMOTE_DEBUGGING}
    volumes:
      - .:/app
